language: python
python:
  - "3.6"
install:
  - pip install -r CI/requirements.txt
  - pip install codecov
  - pip install pytest pytest-cov
script:
  - cd tests
  - pytest --cov=./
  - codecov -t d970060e-74b3-43d8-acfa-7cbb568cf852
